// Hebrew microcopy bank — sourced 1:1 from Screen-Spec-00 §C2.
// Professional, warm, non-shaming. No score/grade words, no "כמה הגיעו", no hype.
export const T = {
  brand: 'GIGPROOF',
  common: {
    continue: 'המשך',
    saveLater: 'שמור והמשך אחר כך',
    back: 'חזור',
    loading: 'טוען…',
    sending: 'שולח…',
    saved: 'נשמר ✓',
    error: 'משהו השתבש. נסה שוב.',
    required: 'שדה חובה',
  },
  login: {
    title: 'ברוך שובך',
    email: 'אימייל',
    password: 'סיסמה',
    cta: 'כניסה',
    secondary: 'אין לך חשבון? הרשמה',
    error: 'אימייל או סיסמה שגויים. נסה שוב.',
  },
  signup: {
    title: 'בוא נבנה לך פרופיל מקצועי',
    name: 'שם',
    email: 'אימייל',
    password: 'סיסמה',
    cta: 'צור חשבון',
    secondary: 'כבר רשום? כניסה',
    error: 'האימייל הזה כבר בשימוש.',
  },
  roleSelect: {
    title: 'מי אתה?',
    agency: 'אני אמרגן / סוכנות',
    artist: 'אני אמן',
    booker: 'אני מזמין / מפיק',
  },
  onboarding: {
    step1Title: 'ספר לנו מי אתה',
    stageName: 'שם במה',
    genre: "ז'אנר",
    city: 'עיר',
    photo: 'העלה תמונה',
    oneLine: 'משפט אחד שמתאר אותך',
    step2Title: 'הקישורים שלך',
    linkPlaceholder: 'הדבק קישור (אינסטגרם / סאונדקלאוד / יוטיוב)',
    linkHelp: 'כל קישור מחזק את הפרופיל',
    step3Title: 'ההוכחות שלך',
    drawHelp: 'הוכחת המשיכה שלך — כטווחים, בלי מספרים מדויקים',
    freqBand: 'תדירות הופעות',
    sellsTickets: 'מוכר כרטיסים בעצמך?',
    priceBand: 'בנד מחיר / גרנטי',
    communityBand: 'גודל קהילה (וואטסאפ / IG)',
    step4Title: 'הניסיון המקצועי שלך',
    addItem: '+ הוסף הופעה / שיתוף פעולה / רֵליס',
    itemHelp: 'הוסף איפה הופעת, עם מי, ואירועים שהפקת',
    step5Title: 'מוכנות להזמנה',
    setLength: 'אורך סט',
    regions: 'אזורים',
    invoice: 'חשבונית (עוסק מורשה)',
    rider: 'העלה райдер טכני',
    step6Title: 'הפרופיל שלך מוכן 🎧',
    publish: 'פרסם פרופיל',
    backToEdit: 'חזור לעריכה',
  },
  dashboard: {
    title: 'הפרופיל המקצועי שלך',
    suggestionsTitle: 'מה יחזק את הפרופיל',
    publishOn: 'פרסום: פעיל',
    publishOff: 'פרסום: כבוי',
    viewPublic: 'צפה בפרופיל הציבורי',
    empty: 'עוד לא בנית פרופיל — בוא נתחיל',
  },
  passport: {
    chip: 'פרופיל מקצועי מאומת',
    cta: 'בדוק זמינות',
    firewall:
      'GIGPROOF מציג עובדות מקצועיות מאומתות לפי מקור. אין כאן הבטחה או ניבוי.',
    proofTitle: 'הוכחת משיכה',
    proofBuilding: 'הוכחת משיכה בבנייה',
    trackRecord: 'ניסיון מקצועי',
    readiness: 'מוכנות להזמנה',
    notFound: 'הפרופיל לא נמצא.',
  },
  request: {
    title: (name) => `בדיקת זמינות — ${name}`,
    subtitle: 'ממלאים פרטים, והאמן יחזור אליך. בלי התחייבות.',
    name: 'שם מלא',
    org: 'ארגון / חברה',
    eventDate: 'תאריך האירוע',
    location: 'מיקום',
    capacity: 'קהל צפוי (טווח)',
    budget: 'תקציב (טווח)',
    message: 'הודעה',
    cta: 'שלח בקשה',
    confirmTitle: '✅ הבקשה נשלחה',
    confirmBody: (name) => `${name} יחזור אליך בקרוב. תודה.`,
  },
  agency: {
    title: 'הסוכנות שלי',
    addArtist: 'הוסף אמן',
    empty: 'הוסף את האמן הראשון',
    requests: 'בקשות זמינות',
    requestsEmpty: 'אין בקשות עדיין',
    markReplied: 'סמן שטופל',
    markClosed: 'סגור',
    statusNew: 'חדש',
    statusReplied: 'טופל',
    statusClosed: 'סגור',
  },
  consent: {
    title: 'הסכמה ופרטיות',
    body: 'אנחנו אוספים רק מידע שאתה מספק או מאשר. אתה שולט במה שמתפרסם, ויכול לתקן או למחוק בכל עת.',
    processing: 'אני מסכים לעיבוד המידע שסיפקתי לצורך בניית הפרופיל.',
    marketing: 'אני מסכים לקבל עדכונים (אופציונלי).',
    accept: 'אני מסכים',
    decline: 'לא עכשיו',
    note: 'הנוסח כיווני עד אישור יועץ משפטי (תיקון 13).',
  },
  evidence: {
    title: 'ההוכחות שלך',
    subtitle: 'העלה קובץ, חבר חשבון, או הזן טווח — כל דרך עוזרת. שום שדה אינו חובה.',
    uploadFile: 'העלה קובץ (אקספורט כרטיסים / סטֵלמנט / צילום מסך)',
    connect: 'חבר חשבון (בקרוב)',
    bandEntry: 'הזן טווח + קישור ציבורי',
    publicUrl: 'קישור ציבורי (אופציונלי)',
    process: 'עבד את ההוכחות',
    processing: 'ה-AI קורא ומסווג…',
  },
  // bounded statuses — the ONLY status vocabulary allowed (firewall)
  status: {
    strong: 'חזק',
    developing: 'מתפתח',
    missing: 'חסר הוכחה',
    notAssessable: 'לא ניתן להעריך',
  },
  // source labels
  source: {
    verified: 'מאומת',
    supporting: 'נתמך',
    selfReported: 'מדווח עצמי',
    publicRecord: 'רישום ציבורי',
    byArtist: 'לפי האמן',
  },
}

// Band option sets (Hebrew display values, stored verbatim)
export const BANDS = {
  frequency: ['מתחיל', '1–3 הופעות', '4–10 הופעות', '10+ הופעות בשנה'],
  price: ['עד ₪2,000', '₪2,000–5,000', '₪5,000–10,000', '₪10,000+'],
  community: ['עד 500', '500–2,000', '2,000–10,000', '10,000+'],
  capacity: ['עד 100', '100–300', '300–800', '800+'],
  budget: ['עד ₪3,000', '₪3,000–8,000', '₪8,000–20,000', '₪20,000+'],
}

export const PROFILE_ITEM_TYPES = [
  { value: 'event', label: 'הופעה / אירוע' },
  { value: 'lineup', label: 'ליינאפ / במה משותפת' },
  { value: 'collab', label: 'שיתוף פעולה' },
  { value: 'release', label: 'רֵליס / יציאה' },
  { value: 'residency', label: 'רזידנסי' },
  { value: 'self_produced_event', label: 'אירוע בהפקה עצמית' },
]
