import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const input = path.join(root, 'src', 'contracts', 'technical-baseline', 'contract.json');
const output = path.join(root, 'src', 'generated', 'technical-baseline.d.ts');
const raw = fs.readFileSync(input, 'utf8');
const contract = JSON.parse(raw);

const union = (values) => [...new Set(values)].sort().map((value) => JSON.stringify(value)).join(' | ') || 'never';
const capabilities = contract.routes.map((route) => route.capability);
const states = contract.designSystem.components.flatMap((component) => component.states);
const hash = crypto.createHash('sha256').update(raw).digest('hex');

const generated = `// Generated by scripts/tech-baseline/generate-types.mjs. Do not edit.\n` +
  `// Contract SHA-256: ${hash}\n` +
  `export type TechnicalBaselineSourceId = ${union(contract.sources.map((source) => source.id))};\n` +
  `export type DesignTokenId = ${union(contract.designSystem.tokens.map((token) => token.id))};\n` +
  `export type DesignComponentId = ${union(contract.designSystem.components.map((component) => component.id))};\n` +
  `export type DesignComponentState = ${union(states)};\n` +
  `export type LocaleMode = ${union(contract.locale.modes)};\n` +
  `export type TaxonomyId = ${union(contract.taxonomy.ids)};\n` +
  `export type RoutePath = ${union(contract.routes.map((route) => route.path))};\n` +
  `export type CapabilityId = ${union(capabilities)};\n` +
  `export type AdminContextPhase = ${union(contract.admin.contextPhases)};\n` +
  `export type RlsNegativeCase = ${union(contract.rls.negatives)};\n` +
  `export type KnownBlockerId = ${union(contract.knownBlockers.map((blocker) => blocker.id))};\n`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(output) ? fs.readFileSync(output, 'utf8') : '';
  if (current !== generated) {
    console.error('GENERATED_TYPES_DRIFT');
    process.exit(1);
  }
  console.log('GENERATED_TYPES_OK');
} else {
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, generated);
  console.log(path.relative(root, output));
}
