// Demo cohort — generated personas, no real people, no real photos (avatars are colour-generated).
// Balanced pool per canon (~4 Growth : 1 Provider liquidity target).

import type { Profile } from "./types";

const now = () => new Date().toISOString();

export const SEED_PROFILES: Profile[] = [
  {
    id: "p_daniel",
    side: "provider",
    displayAlias: "דניאל",
    ageBand: "45-54",
    cityDisplay: "תל אביב",
    professionCategory: "יזם טכנולוגיה",
    goalsPrimary: "קשר משמעותי עם ליווי וצמיחה",
    intentLevel: 4,
    communicationStyle: "warm",
    pacing: "steady",
    visibilityMode: "matches_only",
    premiumTier: "premium",
    verificationStatus: "verified",
    trustSignals: ["verified", "safe_conduct"],
    about: "מאמין שקשר טוב מתחיל בהקשבה. אוהב ים, יין טוב ושיחות עומק.",
    avatarHue: 210,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "p_michael",
    side: "provider",
    displayAlias: "מיכאל",
    ageBand: "35-44",
    cityDisplay: "המרכז",
    professionCategory: "רופא",
    goalsPrimary: "חיבור איכותי בלי משחקים",
    intentLevel: 5,
    communicationStyle: "direct",
    pacing: "fast",
    visibilityMode: "matches_only",
    premiumTier: "elite",
    verificationStatus: "verified",
    trustSignals: ["verified"],
    about: "ישיר, נדיב, עסוק — ומחפש משהו אמיתי, לא עוד אפליקציה.",
    avatarHue: 230,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_noa",
    side: "growth",
    displayAlias: "נועה",
    ageBand: "25-29",
    cityDisplay: "תל אביב",
    professionCategory: "סטודנטית לעיצוב",
    goalsPrimary: "קשר משמעותי עם ליווי וצמיחה",
    intentLevel: 4,
    communicationStyle: "warm",
    pacing: "steady",
    visibilityMode: "matches_only",
    premiumTier: "none",
    verificationStatus: "verified",
    trustSignals: ["verified", "safe_conduct"],
    about: "מעצבת בתחילת הדרך. מחפשת מישהו שמאמין בי באמת — ולא ממהרת לשום מקום.",
    avatarHue: 340,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_maya",
    side: "growth",
    displayAlias: "מאיה",
    ageBand: "30-34",
    cityDisplay: "המרכז",
    professionCategory: "יועצת שיווק",
    goalsPrimary: "חיבור איכותי בלי משחקים",
    intentLevel: 5,
    communicationStyle: "direct",
    pacing: "fast",
    visibilityMode: "open",
    premiumTier: "none",
    verificationStatus: "verified",
    trustSignals: ["verified"],
    about: "עצמאית, חדה, יודעת מה אני רוצה. מעריכה כנות מהמשפט הראשון.",
    avatarHue: 15,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_shira",
    side: "growth",
    displayAlias: "שירה",
    ageBand: "19-24",
    cityDisplay: "חיפה",
    professionCategory: "סטודנטית למשפטים",
    goalsPrimary: "מנטורות ותמיכה אמיתית",
    intentLevel: 3,
    communicationStyle: "playful",
    pacing: "slow",
    visibilityMode: "matches_only",
    premiumTier: "none",
    verificationStatus: "pending",
    trustSignals: [],
    about: "סקרנית, צוחקת הרבה, לומדת קשה. רוצה להכיר לאט ובכיף.",
    avatarHue: 45,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_tamar",
    side: "growth",
    displayAlias: "תמר",
    ageBand: "25-29",
    cityDisplay: "תל אביב",
    professionCategory: "מטפלת באמנות",
    goalsPrimary: "להכיר לאט ולראות לאן זה הולך",
    intentLevel: 3,
    communicationStyle: "reserved",
    pacing: "slow",
    visibilityMode: "matches_only",
    premiumTier: "none",
    verificationStatus: "verified",
    trustSignals: ["verified"],
    about: "שקטה, עמוקה, מאמינה בקשב. מחפשת מישהו סבלני ואמיתי.",
    avatarHue: 160,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_lior",
    side: "growth",
    displayAlias: "ליאור",
    ageBand: "30-34",
    cityDisplay: "השרון",
    professionCategory: "מנהלת מסעדה",
    goalsPrimary: "קשר משמעותי עם ליווי וצמיחה",
    intentLevel: 4,
    communicationStyle: "warm",
    pacing: "steady",
    visibilityMode: "open",
    premiumTier: "none",
    verificationStatus: "verified",
    trustSignals: ["verified", "safe_conduct"],
    about: "אוהבת אנשים, אוכל טוב ושיחות עד הלילה. באתי בשביל האמיתי.",
    avatarHue: 300,
    marketPack: "IL",
    createdAt: now(),
  },
  {
    id: "g_roni",
    side: "growth",
    displayAlias: "רוני",
    ageBand: "25-29",
    cityDisplay: "ירושלים",
    professionCategory: "דוקטורנטית",
    goalsPrimary: "מנטורות ותמיכה אמיתית",
    intentLevel: 4,
    communicationStyle: "direct",
    pacing: "steady",
    visibilityMode: "matches_only",
    premiumTier: "none",
    verificationStatus: "verified",
    trustSignals: ["verified"],
    about: "חוקרת, שאפתנית, ישרה עד כאב. מחפשת שותף לדרך — לא קיצורי דרך.",
    avatarHue: 265,
    marketPack: "IL",
    createdAt: now(),
  },
];
