-- NO PRECONDITION HERE, deliberately — REMOVED after independent QA.
--
-- 044.down's duplicate-pair refusal was hoisted into this file so that a FULL
-- newest-first rollback would refuse BEFORE the guard was dropped, rather than
-- leaving the operator unprotected when 044 refused later. It needed an escape so a
-- 046-only revert stayed possible, and the escape was a session GUC
-- (b4.partial_rollback) that tried to PROVE it was genuinely partial by testing
-- whether 047 was still installed. Both halves failed:
--
--   * ORDER-DEPENDENT (two reviewers, executed independently). The proof only holds
--     newest-first. Running 046.down FIRST in the same session passes the test — 047
--     is still installed — and the chain then dies at 044.down, leaving authority
--     columns present, the guard gone, the trust helper gone, and the grantee
--     self-issuing publish scope with a ten-year expiry. Verbatim the state the
--     precondition was hoisted here to prevent.
--
--   * IT BROKE THE LEGITIMATE CASE. 047 has its own down file and reverting it alone
--     is supported. Afterwards, with Act-scoped grants present — the normal steady
--     state from 044 on — a 046-only revert became IMPOSSIBLE: with the escape it
--     refused ("047 is already gone"), without it the duplicate-pair check refused.
--     The message was factually false and repeated the harmful advice this file had
--     already withdrawn: delete a legitimate Act-scoped grant in order to drop a
--     trigger. The very property the five-way split exists to give was destroyed.
--
-- A property proven by proxy is not proven. The operator's real concern — never being
-- left LESS safe than they started — is served by ATOMICITY, not by a precondition
-- that guesses the operator's intent from session state. Run the full rollback as ONE
-- transaction:
--
--   psql --single-transaction -f 047_grant_decision.down.sql \
--                             -f 046_artist_access_guard.down.sql \
--                             -f 045_artist_access_revocation.down.sql \
--                             -f 044_artist_access_act_key.down.sql \
--                             -f 043_artist_access_columns.down.sql
--
-- Verified by execution with duplicate pairs present: 044.down raises, the whole
-- transaction rolls back, and the guard, grant_permits, the trust helper and the
-- authority columns are all still in place — nothing lost, in ANY file order, WHEN RUN
-- AS ONE TRANSACTION. Independent QA executed all 120 permutations of the five down
-- files under that wrapper: none committed, and none lost state after a refusal.
--
-- THE RESIDUAL, STATED PLAINLY BECAUSE IT IS REAL. That guarantee is about the
-- PROCEDURE, not about this file. Run the five files UNWRAPPED — psql without
-- --single-transaction, or five separate invocations — and 047, 046 and 045 commit one
-- by one, 044 then refuses, and you are left with the authority columns present, the
-- guard gone and the trust helper gone: a grantee can self-issue publish scope and a
-- ten-year expiry until you re-apply. That is the same end state the removed
-- precondition was hoisted here to prevent, and removing it did not make the state
-- unreachable — it made it reachable only by ignoring the documented procedure, rather
-- than by following one of two orderings the precondition itself got wrong. If you are
-- rolling this back, wrap it.
--
-- Asserted by scripts/test-grant-scope.mjs [25d], which executes the unwrapped case
-- and measures that outcome rather than assuming it away.

-- DOWN 046 — remove the authority guard.
--
-- Reverting this RE-OPENS the grantee's ability to write their own authority
-- columns. In a FULL newest-first rollback that is bounded, because 047's decision
-- function is already gone.
--
-- IN THE PARTIAL MODE IT IS NOT BOUNDED, and the previous wording claimed otherwise.
-- After a 046-only revert: 047 is still installed, grant_permits is still granted to
-- `authenticated`, the guard is gone and act_belongs_to_artist is gone with it — so
-- the linkage check disappears too. Independent QA then, as plain `authenticated`,
-- set actions={publish,sign}, scope up to publish, status=active, consent_at=now(),
-- expires_at=+10 years AND pointed act_id at another Person's Act, with
-- grant_permits returning true. If PART B has been applied, that is cross-Person
-- publish. A 046-only revert is therefore an OPERATOR-SUPERVISED window, not a safe
-- resting state: re-apply 046 as soon as the client issue is resolved.
drop trigger if exists trg_artist_access_guard_authority on public.artist_access;
drop function if exists public.artist_access_guard_authority();
drop function if exists public.act_belongs_to_artist(uuid, uuid);
